In [2]:
import torch

In [7]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    print("No GPU found")

No GPU found


### PyTorch Fundamentals

In [ ]:
X = torch.tensor([
    [1, 4, 7],
    [2, 3, 6]
])

X

tensor([[1, 4, 7],
        [2, 3, 6]])

In [10]:
X.shape

torch.Size([2, 3])

In [11]:
X.dtype

torch.int64

In [15]:
X = X.to(torch.float16)

In [17]:
X.dtype

torch.float16

In [18]:
X[0, 1]

tensor(4., dtype=torch.float16)

In [19]:
X[:, 1]

tensor([4., 3.], dtype=torch.float16)

In [20]:
2 * (X + 1)

tensor([[ 4., 10., 16.],
        [ 6.,  8., 14.]], dtype=torch.float16)

In [21]:
X.exp()

tensor([[   2.7188,   54.5938, 1097.0000],
        [   7.3906,   20.0781,  403.5000]], dtype=torch.float16)

In [22]:
X.mean()

tensor(3.8340, dtype=torch.float16)

In [25]:
X.max(dim=0)

torch.return_types.max(
values=tensor([2., 4., 7.], dtype=torch.float16),
indices=tensor([1, 0, 0]))

In [29]:
X.max(dim=1)

torch.return_types.max(
values=tensor([7., 6.], dtype=torch.float16),
indices=tensor([2, 2]))

In [31]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]], dtype=torch.float16)

A NumPy array to a tensor, it’s best to specify dtype=torch.float32.
Alternatively, you can use torch.FloatTensor() which automatically converts the
array to 32 bits

In [32]:
import numpy as np

torch.FloatTensor(
    np.array([
        [1, 4, 7],
        [2, 3, 6]
    ])
)

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [33]:
X.abs()

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float16)

In [34]:
X.sqrt()

tensor([[1.0000, 2.0000, 2.6465],
        [1.4141, 1.7324, 2.4492]], dtype=torch.float16)

In [36]:
X.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [38]:
X = torch.tensor([
    [1, -99, 7],
    [2, -99, 6]
])
X

tensor([[  1, -99,   7],
        [  2, -99,   6]])

In [42]:
X.relu_()

tensor([[1, 0, 7],
        [2, 0, 6]])