In [2]:
import torch

In [3]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    print("No GPU found")

No GPU found


### PyTorch Fundamentals

In [4]:
X = torch.tensor([
    [1, 4, 7],
    [2, 3, 6]
])

X

tensor([[1, 4, 7],
        [2, 3, 6]])

In [5]:
X.shape

torch.Size([2, 3])

In [6]:
X.dtype

torch.int64

In [7]:
X = X.to(torch.float16)

In [8]:
X.dtype

torch.float16

In [9]:
X[0, 1]

tensor(4., dtype=torch.float16)

In [10]:
X[:, 1]

tensor([4., 3.], dtype=torch.float16)

In [11]:
2 * (X + 1)

tensor([[ 4., 10., 16.],
        [ 6.,  8., 14.]], dtype=torch.float16)

In [12]:
X.exp()

tensor([[   2.7188,   54.5938, 1097.0000],
        [   7.3906,   20.0781,  403.5000]], dtype=torch.float16)

In [13]:
X.mean()

tensor(3.8340, dtype=torch.float16)

In [14]:
X.max(dim=0)

torch.return_types.max(
values=tensor([2., 4., 7.], dtype=torch.float16),
indices=tensor([1, 0, 0]))

In [15]:
X.max(dim=1)

torch.return_types.max(
values=tensor([7., 6.], dtype=torch.float16),
indices=tensor([2, 2]))

In [16]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]], dtype=torch.float16)

A NumPy array to a tensor, it’s best to specify dtype=torch.float32.
Alternatively, you can use torch.FloatTensor() which automatically converts the
array to 32 bits

In [17]:
import numpy as np

torch.FloatTensor(
    np.array([
        [1, 4, 7],
        [2, 3, 6]
    ])
)

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [ ]:
X.abs()

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float16)

In [ ]:
X.sqrt()

tensor([[1.0000, 2.0000, 2.6465],
        [1.4141, 1.7324, 2.4492]], dtype=torch.float16)

In [ ]:
X.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [ ]:
X = torch.tensor([
    [1, -99, 7],
    [2, -99, 6]
])
X

tensor([[  1, -99,   7],
        [  2, -99,   6]])

In [ ]:
X.relu_()

tensor([[1, 0, 7],
        [2, 0, 6]])

In [24]:
### A Learning Rate (LR) Scheduler is a technique in deep learning that automatically adjusts the optimizer's learning rate during training, usually reducing it over time.