# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
dim1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
dim2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
dim3 = np.array([[[1, 2], [3, 4]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(dim1.shape)
print(dim1.ndim)
print(dim1.dtype)
print(dim1.size)
print(type(dim1))

(3,)
1
int64
3
<class 'numpy.ndarray'>


In [9]:
# Attributes of 2-dimensional array
print(dim2.shape)
print(dim2.ndim)
print(dim2.dtype)
print(dim2.size)
print(type(dim2))

(2, 3)
2
int64
6
<class 'numpy.ndarray'>


In [10]:
# Attributes of 3-dimensional array
print(dim3.shape)
print(dim3.ndim)
print(dim3.dtype)
print(dim3.size)
print(type(dim3))

(1, 2, 2)
3
int64
4
<class 'numpy.ndarray'>


In [16]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(dim2)
df.columns = ['one', 'two', 'three']
df

,one,two,three
0,1,2,3
1,4,5,6


In [19]:
# Create an array of shape (10, 2) with only ones
array_10_2 = np.ones((10, 2), dtype=int)
array_10_2

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [21]:
# Create an array of shape (7, 2, 3) of only zeros
array_7_2_3 = np.zeros((7, 2, 3), dtype=int)
array_7_2_3

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [25]:
# Create an array within a range of 0 and 100 with step 3
array_ranges = np.arange(0, 100, 3)
array_ranges

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [34]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7, 2))
random_array

array([[4, 9],
       [8, 8],
       [6, 5],
       [3, 4],
       [0, 5],
       [9, 6],
       [5, 4]], dtype=int32)

In [40]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_flts = np.random.uniform(0, 1, (3, 5))
random_array_flts2 = np.random.rand(3, 5)
print(random_array_flts)
print('-----'*10 + '--------')
print(random_array_flts2)

[[0.22787011 0.48722608 0.17841332 0.09513658 0.71481907]
 [0.16688347 0.59947212 0.55025578 0.2586592  0.98220824]
 [0.34041963 0.09100708 0.4402025  0.77253676 0.88931461]]
----------------------------------------------------------
[[0.14752587 0.11256218 0.22883139 0.40603019 0.5759976 ]
 [0.36526282 0.50280818 0.34623433 0.71748092 0.43359397]
 [0.50038905 0.84253707 0.54905438 0.03145409 0.94513569]]


In [45]:
# Set the random seed to 42
rng = np.random.default_rng(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr = rng.integers(0, 10, size=(4, 6))
print(arr)

[[0 7 6 4 4 8]
 [0 6 2 0 5 9]
 [7 7 7 7 5 1]
 [8 4 5 3 1 9]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [49]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_numbers = np.random.randint(1, 10, (3, 7))

# Find the unique numbers in the array you just created
unique_numbers = np.unique(random_numbers)
unique_numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [51]:
# Find the 0'th index of the latest array you created
random_numbers[0]

array([6, 3, 3, 3, 3, 8, 6], dtype=int32)

In [53]:
# Get the first 2 rows of latest array you created
random_numbers[:2]

array([[6, 3, 3, 3, 3, 8, 6],
       [9, 6, 4, 2, 5, 6, 2]], dtype=int32)

In [55]:
# Get the first 2 values of the first 2 rows of the latest array
random_numbers[:2, :2]

array([[6, 3],
       [9, 6]], dtype=int32)

In [95]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_of_nums = np.random.randint(low=0, high=10, size=(3, 5))
arr_of_ones = np.ones(shape=(3, 5))
arr_of_nums

array([[9, 4, 2, 0, 6],
       [7, 6, 7, 8, 7],
       [9, 7, 1, 7, 0]], dtype=int32)

In [96]:
arr_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [97]:
# Add the two arrays together
arr_of_nums + arr_of_ones

array([[10.,  5.,  3.,  1.,  7.],
       [ 8.,  7.,  8.,  9.,  8.],
       [10.,  8.,  2.,  8.,  1.]])

In [102]:
# Create another array of ones of shape (5, 3)
arr_of_ones2 = np.ones(shape=(5, 3))

In [103]:
# Try add the array of ones and the other most recent array together
arr_of_ones2 + arr_of_ones

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [104]:
# Create another array of ones of shape (3, 5)
arr_of_ones3 = np.ones(shape=(3, 5))

In [107]:
# Subtract the new array of ones from the other most recent array
arr_of_ones3 - arr_of_ones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [108]:
# Multiply the ones array with the latest array
arr_of_ones3 * arr_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [109]:
# Take the latest array to the power of 2 using '**'
arr_of_ones3 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [110]:
# Do the same thing with np.square()
np.square(arr_of_ones3)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [111]:
# Find the mean of the latest array using np.mean()
np.mean(arr_of_ones3)

np.float64(1.0)

In [112]:
# Find the maximum of the latest array using np.max()
np.max(arr_of_ones3)

np.float64(1.0)

In [113]:
# Find the minimum of the latest array using np.min()
np.min(arr_of_ones3)

np.float64(1.0)

In [121]:
variance = ((arr_of_nums - arr_of_nums.mean())**2).mean()
std_dev = np.sqrt(variance)
std_dev1 = arr_of_nums.std()
print(std_dev)
print(std_dev1)

3.025814858109391
3.025814858109391


In [130]:
# Find the variance of the latest array
variance

np.float64(9.155555555555555)

In [131]:
# Reshape the latest array to (3, 5, 1)
arr_of_ones2.shape
arr_of_ones2.reshape((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [135]:
# Transpose the latest array
arr_of_ones2.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(0, 10, size=(3, 3))
arr2 = np.random.randint(0, 10, size=(3, 2))

In [139]:
arr1

array([[8, 8, 0],
       [5, 8, 4],
       [8, 9, 4]], dtype=int32)

In [140]:
arr2

array([[0, 2],
       [1, 9],
       [4, 2]], dtype=int32)

In [137]:
# Perform a dot product on the two newest arrays you created
arr1 @ arr2

array([[  8,  88],
       [ 24,  90],
       [ 25, 105]], dtype=int32)

In [143]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 = np.random.randint(0, 10, size=(4, 3))
arr4 = np.random.randint(0, 10, size=(4, 3))

In [144]:
# Perform a dot product on the two newest arrays you created
arr3 @ arr4

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

It doesn't work. How would you fix it?

In [145]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr3 @ arr4.T

array([[ 33,  58,  78,  82],
       [ 30,  61,  64,  77],
       [ 70,  28,  79, 100],
       [ 24,  18,  39,  42]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [146]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array1 = np.random.randint(0, 10, size=(2, 5))
array2 = np.random.randint(0, 10, size=(2, 5))

In [147]:
# Compare the two arrays with '>'
array1 > array2

array([[ True,  True, False, False,  True],
       [ True,  True, False, False,  True]])

What happens when you compare the arrays with `>`?

In [148]:
# Compare the two arrays with '>='
array1 >= array2

array([[ True,  True, False, False,  True],
       [ True,  True, False,  True,  True]])

In [149]:
# Find which elements of the first array are greater than 7
array1 > 7

array([[False, False, False, False, False],
       [False, False,  True, False,  True]])

In [152]:
# Which parts of each array are equal? (try using '==')
array1 == array2

array([[False, False, False, False, False],
       [False, False, False,  True, False]])

In [161]:
# Sort one of the arrays you just created in ascending order
np.sort(array1, axis=1)

array([[1, 3, 3, 5, 6],
       [1, 5, 6, 8, 8]], dtype=int32)

In [162]:
# Sort the indexes of one of the arrays you just created
np.argsort(array2, axis=1)

array([[4, 0, 1, 2, 3],
       [0, 3, 4, 1, 2]])

In [172]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array1)

np.int64(7)

In [171]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array1)

np.int64(2)

In [173]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array1, axis=1)

array([0, 2])

In [174]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array1, axis=0)

array([1, 0, 0, 1, 0])

In [177]:
# Create an array of normally distributed random numbers
normal_dist = np.random.normal(0, 1, 10)
normal_dist

array([-0.33415962, -0.17211509, -0.30998366, -1.8417733 , -0.39905273,
       -1.10027486,  1.63651556,  0.83174878,  0.39370483,  0.71926374])

In [182]:
# Create an array with 10 evenly spaced numbers between 1 and 100
ten_even = np.linspace(1, 100, 10)
ten_even

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.