### Exercise 1: Basic Arithmetic

In [3]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(3 * x)
print(x ** 2)

[5 7 9]
[3 6 9]
[1 4 9]


### Exercise 2: Universal Functions

In [8]:
z = np.array([1, 4, 9, 16, 25])
sqrt_z = np.sqrt(z)

angles = np.array([0, np.pi/2, np.pi])
sin_angles = np.sin(angles)

print(sqrt_z)
print(sin_angles)

[1. 2. 3. 4. 5.]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]


### Exercise 3: Broadcasting

In [12]:
matrix = np.arange(1, 10).reshape(3, 3)
vector = np.array([10, 20, 30])
different_sized_vector = np.array([100, 200])

Sum = vector + matrix
print(Sum)

try:
    print(different_sized_vector + matrix)
except Exception as e:
    print(e)


[[11 22 33]
 [14 25 36]
 [17 28 39]]
operands could not be broadcast together with shapes (2,) (3,3) 


### Exercise 4: Aggregate Functions

In [ ]:
data = np.random.randint(1, 100, size=(3, 5))
print(data)

print(np.sum(data))
print(np.mean(data))
print(np.max(data))

print(np.sum(data, axis = 0))
print(np.mean(data, axis = 1))

[[10 77 24 56 99]
 [19 76 55 64 22]
 [25 67 32 69 63]]
758
50.53333333333333
99
[ 54 220 111 189 184]
[18.         73.33333333 37.         63.         61.33333333]


### Exercise 5: Reshaping Arrays

In [40]:
arr = np.linspace(0, 11, 12)
arr2 = arr.reshape(3, 4)
arr3 = arr2.reshape(4, 3)
arr4 = arr3.reshape(2, 2, 3)

print(arr)
print('\n')
print(arr2)
print('\n')
print(arr3)
print('\n')
print(arr4)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


### Exercise 6: Stacking Arrays

In [46]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

mh = np.hstack((m1, m2))
mv = np.vstack((m1, m2))

print(mh)
print(mv)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Exercise 7: Boolean Indexing

In [52]:
nums = np.arange(-5, 6, 1)

mask = nums > 0
print(nums[mask])
nums[nums < 0] = 0 
print(nums)

[1 2 3 4 5]
[0 0 0 0 0 0 1 2 3 4 5]


### Exercise 8: Dot Product and Matrix Multiplication

In [59]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(f'Dot product of v1 and v2 = {v1 @ v2}')

mat1 = np.arange(1, 5, 1).reshape(2, 2)
mat2 = np.arange(5, 9, 1).reshape(2, 2)

print(f'Dot product of mat1 and mat2 with @')
print(mat1 @ mat2)
print(f'Dot product of mat1 and mat2 with np.dot')
print(np.dot(mat1, mat2))

Dot product of v1 and v2 = 32
Dot product of mat1 and mat2 with @
[[19 22]
 [43 50]]
Dot product of mat1 and mat2 with np.dot
[[19 22]
 [43 50]]
