In [65]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a_1 = np.array([[1, 2, 3], [4, 5, 6]])
a_2 = np.array([
        [
            [1, 2, 3], [4, 5, 6], [7, 8, 9]
        ], 
        [
            [1, 2, 3], [4, 5, 6], [7, 8, 9]
        ]
    ])

print(a + b)

print(a.ndim)
print(a.size)
print(a_1.shape)
print(a.shape)
print(a_1.ndim)

print(a_2.ndim)
print(a_2.shape)

print(a_2.flatten())
x = a_2.flat

for i in x:
    print(i)

[5 7 9]
1
3
(2, 3)
(3,)
2
3
(2, 3, 3)
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


In [61]:
a = np.zeros((2, 3), dtype=int)
b = np.ones((2, 3), dtype=int)
c = np.full((2, 3), 2, dtype=int)
d = np.empty((2, 3), dtype=int)
e = np.arange(0, 10, 2)
f = np.linspace(0, 10, 10, dtype=int)
g = np.random.uniform(0, 1)
i = np.random.normal(0, 1)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(i)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]]
[[2 2 2]
 [2 2 2]]
[0 2 4 6 8]
[ 0  1  2  3  4  5  6  7  8 10]
0.8187719775478051
-0.5461044548199125


In [38]:
import numpy as np

def funct(a, b, c):
    return a + b*10 + c*100

arr = np.fromfunction(funct, (2, 3, 4), dtype=int)
print(arr)
print('\n')
# for i, n in enumerate(arr):
#     print(i)
#     print(n)

# print(arr[0, 2, 1:3])
# flat = arr.flatten()
# print(flat)
# print(flat.reshape(2, 2, 3, 2))
# print(arr[:, :, 1:])

# indexes = [0,1]
# print(arr[0, indexes])

# rows = [0, 1]
# columns = [0, 2]

# print(arr[np.ix_(rows, columns)])

print(arr[~(arr > 50)])

[[[  0 100 200 300]
  [ 10 110 210 310]
  [ 20 120 220 320]]

 [[  1 101 201 301]
  [ 11 111 211 311]
  [ 21 121 221 321]]]


[ 0 10 20  1 11 21]


In [41]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[(arr >= 2) & (arr <= 3)])
print(arr[(arr >= 4) | (arr <= 1)])

[2 3]
[1 4]


# Numerical Computing with NumPy

In [4]:
import numpy as np
a = np.linspace(0, 100, 2, dtype=int)
b = np.linspace(0, 10, 2).astype('int')

print(a + b)

[  0 110]


In [7]:
import numpy as np

arr1 = np.full((2, 3), 7)
arr2 = np.full((2, 3), 100)

print(arr1)
print(arr2)

np.concatenate([arr1, arr2], axis = 1)
print(arr1.sum(axis=0))


[[7 7 7]
 [7 7 7]]
[[100 100 100]
 [100 100 100]]
[14 14 14]


In [13]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 1]]])
print(a.max(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 1]]


^C
Note: you may need to restart the kernel to use updated packages.
