### Exercise 1: Creating Arrays

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.zeros(10)
arr4 = np.ones((3, 4))
arr5 = np.arange(0, 9)
arr6 = np.linspace(0, 1, 5)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8]
[0.   0.25 0.5  0.75 1.  ]


### Exercise 2: Array Attributes

In [18]:
random_arr = np.random.randint(1, 100, size=(3, 3))
print(random_arr)
print(random_arr.shape)
print(random_arr.ndim)
print(random_arr.size)
print(random_arr.dtype)

[[21 12 19]
 [24 37  8]
 [45 53  8]]
(3, 3)
2
9
int32


### Exercise 3: Indexing and Slicing

In [24]:
a = np.arange(10, 19)
print(f'a = {a}')
print(a[3])
print(a[2:5])

b = np.arange(1, 17).reshape(4, 4)
print(f'b = {b}')
print(b[2, 3])
print(b[:2, -2:])
print(b[:, 2])

a = [10 11 12 13 14 15 16 17 18]
13
[12 13 14]
b = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
12
[[3 4]
 [7 8]]
[ 3  7 11 15]
