In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### System: 
### 170theta1 + 25theta2 + theta3 = 7
### 180theta1 + 30theta2 + theta3 = 8
### 200theta1 + 35theta2 + theta3 = 12


In [2]:
X = np.array([
    [170, 25, 1],
    [180, 30, 1],
    [200, 35, 1]
])
y = np.array([7, 8, 12])

theta = np.linalg.inv(X) @ y
theta

array([  0.3,  -0.4, -34. ])

In [3]:
theta_lina = np.linalg.solve(X, y)
theta_lina

array([  0.3,  -0.4, -34. ])

### If inverse of X doesn't exist

In [ ]:
X_1 = np.array([
    [170, 25, 1],
    [180, 30, 1],
    [200, 35, 1],
    [160, 20, 1]
])
y_1 = np.array([7, 8, 12, 15])

theta_1 = np.linalg.inv(X_1) @ y
theta_1
### ERROR

In [10]:
theta_1_pinv = np.linalg.pinv(X_1) @ y_1
theta_1_pinv

array([  0.9,  -2.5, -80.5])

In [11]:
160 * 0.9 + 20 * (-2.5) + 1 * (-80.5)

13.5

In [15]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_1[:, :-1], y_1)
lin_reg.intercept_, lin_reg.coef_

(np.float64(-80.50000000000001), array([ 0.9, -2.5]))